# Font configuration
font_family      Terminess Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# Window layout & Padding
window_padding_width 12

# Opacity
background_opacity 0.75

# Cursor
cursor           #ffffff
cursor_shape     block
shell_integration disabled

# Color
foreground              #ffffff
background              #000000
cursor                  #eeeeee
cursor_text_color       #121212

selection_foreground    #121212
selection_background    #eeeeee

color0  #1c1c1c
color1  #4e4e4e
color2  #767676
color3  #949494
color4  #acacac
color5  #c6c6c6
color6  #e4e4e4
color7  #eeeeee

color8  #444444
color9  #626262
color10 #8a8a8a
color11 #b0b0b0
color12 #c6c6c6
color13 #dadada
color14 #f0f0f0
color15 #ffffff
